package SoftwareComponentLanguage.sandbox.Testing;

/*Generated by MPS */

import java.util.Objects;
import wrappers.javaWrappers.BasicInputOutput;

/**
 * foo
 */
public class AssertTrue {
  public static void AssertTrue(Object expected) {
    if (!(Objects.equals(expected, true))) {
      BasicInputOutput.WriteLine("FAILED: condition is not true");
    }
  }
}
