package SoftwareComponentLanguage.sandbox.Testing;

/*Generated by MPS */

import java.util.Objects;
import wrappers.javaWrappers.BasicInputOutput;

/**
 * foo
 */
public class AssertFalseWithMessage {
  public static void AssertFalseWithMessage(Object expected, String message) {
    if (!(Objects.equals(expected, false))) {
      BasicInputOutput.WriteLine("FAILED: " + message);
    }
  }
}
