package SoftwareComponentLanguage.sandbox.Testing;

/*Generated by MPS */

import java.util.Objects;
import wrappers.javaWrappers.BasicInputOutput;

/**
 * foo
 */
public class AssertEqual {
  public static void AssertEqual(Object expected, Object actual) {
    if (!(Objects.equals(expected, actual))) {
      BasicInputOutput.WriteLine("FAILED: not equal ");
      String actualAsString = (String) actual;
      if (!(Objects.equals(actualAsString, null))) {
        BasicInputOutput.WriteLine("\"" + actualAsString + "\"");
      } else {
        BasicInputOutput.WriteLine("null");
      }
    }
  }
}
