package SoftwareComponentLanguage.sandbox.MyPackage;

/*Generated by MPS */


public class MyComposite implements IMyInterface {
  public MyComposite() {
    this.numberComponent = new NumberComponent();
    this.randomProvider = new RandomProvider();
    this.randomProvider.dependency_GetNumber = this.numberComponent;
  }
  @Override
  public Integer GenerateInt(Integer offset) {
    return this.randomProvider.GenerateInt(offset);
  }
  @Override
  public Integer MyFactor() {
    return this.numberComponent.MyFactor();
  }
  public NumberComponent numberComponent;
  public RandomProvider randomProvider;
}
