package SoftwareComponentLanguage.sandbox.MyPackage;

/*Generated by MPS */


public class NumberComponent implements IMyInterface {
  public NumberComponent() {
  }
  @Override
  public Integer GenerateInt(Integer offset) {
    this.foo = this.foo * this.bar + this.MyFactor();
    return this.foo + offset;
  }
  @Override
  public Integer MyFactor() {
    return 42;
  }
  public Integer foo = 1;
  private Integer bar = 3;
}
