package SoftwareComponentLanguage.sandbox.MyPackage;

/*Generated by MPS */


public class RandomProvider implements IMyInterface {
  public RandomProvider() {
  }
  @Override
  public Integer GenerateInt(Integer offset) {
    return this.dependency_GetNumber.GenerateInt(offset);
  }
  @Override
  public Integer MyFactor() {
    return this.dependency_GetNumber.MyFactor();
  }
  public IMyInterface dependency_GetNumber;
}
