package SoftwareComponentLanguage.sandbox;

/*Generated by MPS */

import org.junit.jupiter.api.Test;
import SoftwareComponentLanguage.sandbox.Order.Webstore;

public class Webstore_ComponentTest_Test {
  @Test
  public void test_testCase() throws Exception {
    Webstore sut = new Webstore();
    sut.addProduct(1);
  }
}
