package HamsterSimulatorLanguage.sandbox.Testing;

/*Generated by MPS */

import java.util.Objects;
import wrappers.javaWrappers.BasicInputOutput;

/**
 * foo
 */
public class AssertFalse {
  public static void AssertFalse(Object expected) {
    if (!(Objects.equals(expected, false))) {
      BasicInputOutput.WriteLine("FAILED: condition is not false");
    }
  }
}
