package HamsterSimulatorLanguage.sandbox.Testing;

/*Generated by MPS */

import java.util.Objects;
import wrappers.javaWrappers.BasicInputOutput;

/**
 * foo
 */
public class AssertTrueWithMessage {
  public static void AssertTrueWithMessage(Object expected, String message) {
    if (!(Objects.equals(expected, true))) {
      BasicInputOutput.WriteLine("FAILED: " + message);
    }
  }
}
