package HamsterSimulatorLanguage.sandbox.Testing;

/*Generated by MPS */

import java.util.Objects;
import wrappers.javaWrappers.BasicInputOutput;

/**
 * foo
 */
public class AssertEqualWithMessage {
  public static void AssertEqualWithMessage(Object expected, Object actual, String message) {
    if (!(Objects.equals(expected, actual))) {
      BasicInputOutput.WriteLine("FAILED: " + message);
    }
  }
}
