package SoftwareComponentLanguage.sandbox.Order;

/*Generated by MPS */

import java.util.List;

public interface IInventoryInterface {
  void addProductItems(Integer productId, Integer amount);
  void removeProductItems(Integer productId, Integer amount);
  List<Integer> getProductIds();
  String getProductName(Integer productId);
  Integer getProductItemsAmount(Integer productId);
}
