package SoftwareComponentLanguage.sandbox.Order;

/*Generated by MPS */

import java.util.Iterator;
import SoftwareComponentLanguage.sandbox.ProductStock;
import java.util.Objects;
import java.util.List;
import java.util.ArrayList;
import java.util.LinkedList;

public class Inventory implements IInventoryInterface, ISearchInterface {
  public Inventory() {
  }
  @Override
  public void addProductItems(Integer productId, Integer amount) {
    {
      // was a for loop
      Iterator<ProductStock> forLoop_zdlsim_a0b0_mainIterator = this.products.iterator();
      while (forLoop_zdlsim_a0b0_mainIterator.hasNext()) {
        ProductStock productStock = forLoop_zdlsim_a0b0_mainIterator.next();

        if (Objects.equals(productStock.id, productId)) {
          productStock.amount = productStock.amount + amount;
          break;
        }
      }
    }
  }
  @Override
  public void removeProductItems(Integer productId, Integer amount) {
    {
      // was a for loop
      Iterator<ProductStock> forLoop_zdlsim_a0c0_mainIterator = this.products.iterator();
      while (forLoop_zdlsim_a0c0_mainIterator.hasNext()) {
        ProductStock productStock = forLoop_zdlsim_a0c0_mainIterator.next();

        if (Objects.equals(productStock.id, productId)) {
          productStock.amount = productStock.amount - amount;
          break;
        }
      }
    }
  }
  @Override
  public List<Integer> getProductIds() {
    List<Integer> result = new ArrayList<>();
    {
      // was a for loop
      Iterator<ProductStock> forLoop_zdlsim_b0d0_mainIterator = this.products.iterator();
      while (forLoop_zdlsim_b0d0_mainIterator.hasNext()) {
        ProductStock productStock = forLoop_zdlsim_b0d0_mainIterator.next();

        result.add(productStock.id);
      }
    }
    return result;
  }
  @Override
  public Integer getProductItemsAmount(Integer productId) {
    {
      // was a for loop
      Iterator<ProductStock> forLoop_zdlsim_a0e0_mainIterator = this.products.iterator();
      while (forLoop_zdlsim_a0e0_mainIterator.hasNext()) {
        ProductStock productStock = forLoop_zdlsim_a0e0_mainIterator.next();

        if (Objects.equals(productStock.id, productId)) {
          return productStock.amount;
        }
      }
    }
    return 0;
  }
  @Override
  public String getProductName(Integer productId) {
    {
      // was a for loop
      Iterator<ProductStock> forLoop_zdlsim_a0f0_mainIterator = this.products.iterator();
      while (forLoop_zdlsim_a0f0_mainIterator.hasNext()) {
        ProductStock productStock = forLoop_zdlsim_a0f0_mainIterator.next();

        if (Objects.equals(productStock.id, productId)) {
          return productStock.name;
        }
      }
    }
    return "";
  }
  @Override
  public Integer searchProduct(String productName) {
    {
      // was a for loop
      Iterator<ProductStock> forLoop_zdlsim_a0g0_mainIterator = this.products.iterator();
      while (forLoop_zdlsim_a0g0_mainIterator.hasNext()) {
        ProductStock productStock = forLoop_zdlsim_a0g0_mainIterator.next();

        if (Objects.equals(productStock.name, productName)) {
          return productStock.id;
        }
      }
    }
    return 0;
  }
  public List<ProductStock> products = new LinkedList<>();
}
