package SoftwareComponentLanguage.sandbox.Order;

/*Generated by MPS */


public interface IOrderManagementInterface {
  void addOrder(Integer productId, Integer amount);
  void removeOrder(Integer productId);
  void orderProducts();
}
