package SoftwareComponentLanguage.sandbox.Order;

/*Generated by MPS */


public interface IShoppingInterface {
  void addProduct(Integer productId);
  void removeProduct(Integer productId);
  void orderProducts();
}
