package SoftwareComponentLanguage.sandbox.Order;

/*Generated by MPS */

import SoftwareComponentLanguage.sandbox.OrderInfo;
import java.util.Iterator;
import java.util.Objects;
import wrappers.javaWrappers.BasicInputOutput;
import wrappers.javaWrappers.IntegerFunctions;
import java.util.List;
import java.util.LinkedList;

public class Ordering implements IOrderManagementInterface {
  public Ordering() {
  }
  @Override
  public void addOrder(Integer productId, Integer amount) {
    OrderInfo order = new OrderInfo();
    order.productId = productId;
    order.amount = amount;
    this.orders.add(order);
  }
  @Override
  public void removeOrder(Integer productId) {
    {
      // was a for loop
      Iterator<OrderInfo> forLoop_aqoliy_a0c0_mainIterator = this.orders.iterator();
      while (forLoop_aqoliy_a0c0_mainIterator.hasNext()) {
        OrderInfo order = forLoop_aqoliy_a0c0_mainIterator.next();

        if (Objects.equals(order.productId, productId)) {
          this.orders.remove(order);
          break;
        }
      }
    }
  }
  @Override
  public void orderProducts() {
    {
      // was a for loop
      Iterator<OrderInfo> forLoop_aqoliy_a0d0_mainIterator = this.orders.iterator();
      while (forLoop_aqoliy_a0d0_mainIterator.hasNext()) {
        OrderInfo order = forLoop_aqoliy_a0d0_mainIterator.next();

        this.dependency_ManageInventory.removeProductItems(order.productId, order.amount);
        String productName = this.dependency_ManageInventory.getProductName(order.amount);
        BasicInputOutput.WriteLine("Finish ordering " + IntegerFunctions.ToString(order.amount) + "x " + productName);
      }
    }
    this.orders.clear();
  }
  public List<OrderInfo> orders = new LinkedList<>();
  public IInventoryInterface dependency_ManageInventory;
}
