package SoftwareComponentLanguage.sandbox.Order;

/*Generated by MPS */

import java.util.List;
import java.util.Iterator;
import java.util.Objects;

public class Searching implements ISearchInterface {
  public Searching() {
  }
  @Override
  public Integer searchProduct(String productName) {
    List<Integer> productIds = this.dependency_SearchInventory.getProductIds();
    {
      // was a for loop
      Iterator<Integer> forLoop_v9woel_b0b0_mainIterator = productIds.iterator();
      while (forLoop_v9woel_b0b0_mainIterator.hasNext()) {
        Integer productId = forLoop_v9woel_b0b0_mainIterator.next();

        String name = this.dependency_SearchInventory.getProductName(productId);
        if (Objects.equals(name, productName)) {
          return productId;
        }
      }
    }
    return -1;
  }
  public IInventoryInterface dependency_SearchInventory;
}
