package SoftwareComponentLanguage.sandbox.Order;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;
import wrappers.javaWrappers.IntegerFunctions;
import java.util.Iterator;
import java.util.List;
import java.util.LinkedList;

public class ShoppingCart implements IShoppingInterface {
  public ShoppingCart() {
  }
  @Override
  public void addProduct(Integer productId) {
    this.products.add(productId);
    BasicInputOutput.WriteLine("Added product " + IntegerFunctions.ToString(productId));
  }
  @Override
  public void removeProduct(Integer productId) {
    this.products.remove(productId);
    BasicInputOutput.WriteLine("Removed product " + IntegerFunctions.ToString(productId));
  }
  @Override
  public void orderProducts() {
    {
      // was a for loop
      Iterator<Integer> forLoop_ntpi04_a0d0_mainIterator = this.products.iterator();
      while (forLoop_ntpi04_a0d0_mainIterator.hasNext()) {
        Integer productId = forLoop_ntpi04_a0d0_mainIterator.next();

        this.dependency_OrderManagement.addOrder(productId, 1);
      }
    }
    this.dependency_OrderManagement.orderProducts();
    this.products.clear();
    BasicInputOutput.WriteLine("Ordered products");
  }
  private List<Integer> products = new LinkedList<>();
  public IOrderManagementInterface dependency_OrderManagement;
}
