package SoftwareComponentLanguage.sandbox.Order;

/*Generated by MPS */


public class Webstore implements ISearchInterface, IShoppingInterface {
  public Webstore() {
    this.searching = new Searching();
    this.shoppingCart = new ShoppingCart();
    this.inventory = new Inventory();
    this.ordering = new Ordering();
    this.shoppingCart.dependency_OrderManagement = this.ordering;
    this.searching.dependency_SearchInventory = this.inventory;
    this.ordering.dependency_ManageInventory = this.inventory;
  }
  @Override
  public Integer searchProduct(String productName) {
    return this.inventory.searchProduct(productName);
  }
  @Override
  public void addProduct(Integer productId) {
    this.shoppingCart.addProduct(productId);
  }
  @Override
  public void removeProduct(Integer productId) {
    this.shoppingCart.removeProduct(productId);
  }
  @Override
  public void orderProducts() {
    this.shoppingCart.orderProducts();
  }
  public Searching searching;
  public ShoppingCart shoppingCart;
  public Inventory inventory;
  public Ordering ordering;
}
