package HamsterSimulatorLanguage.sandbox.HamsterLibrary;

/*Generated by MPS */


public class Cell {
  public Cell north;
  public Cell south;
  public Cell east;
  public Cell west;

  public Boolean isWall = false;
  public Integer grainCount = 0;
}
