package HamsterSimulatorLanguage.sandbox.HamsterLibrary;

/*Generated by MPS */

import wrappers.javaWrappers.BasicInputOutput;
import java.util.Objects;
import java.util.List;
import java.util.LinkedList;

public class Hamster {
  public Hamster(Cell cell) {
    this.currentCell = (cell != null ? cell : new Cell());
  }

  public void pickGrain() {
    if (this.currentCell.grainCount > 0) {
      BasicInputOutput.WriteLine("Picking grain!");
      this.grainInMouth = this.grainInMouth + 1;
      this.currentCell.grainCount = this.currentCell.grainCount - 1;
    } else {
      BasicInputOutput.WriteLine("Failed to pick grain");
    }
  }
  public void putGrain() {
    if (this.grainInMouth > 0) {
      BasicInputOutput.WriteLine("Putting grain!");
      this.grainInMouth = this.grainInMouth - 1;
      this.currentCell.grainCount = this.currentCell.grainCount + 1;
    } else {
      BasicInputOutput.WriteLine("Failed to put grain");
    }
  }
  public void move() {
    Cell frontCell = this.getFrontCell();
    if (!(Objects.equals(frontCell, null))) {
      if (frontCell.isWall) {
        BasicInputOutput.WriteLine("Failed to move, front is wall");
      } else {
        BasicInputOutput.WriteLine("Moving!");
        this.currentCell = frontCell;
      }
    } else {
      BasicInputOutput.WriteLine("Failed to move, front is out of territory");
    }
  }
  public void turnLeft() {
    BasicInputOutput.WriteLine("Turning left!");
    if (Objects.equals(this.currentDirection, Direction.EAST)) {
      this.currentDirection = Direction.NORTH;
    } else if (Objects.equals(this.currentDirection, Direction.SOUTH)) {
      this.currentDirection = Direction.EAST;
    } else if (Objects.equals(this.currentDirection, Direction.WEST)) {
      this.currentDirection = Direction.SOUTH;
    } else {
      this.currentDirection = Direction.WEST;
    }
  }
  public void write(String text) {
    BasicInputOutput.WriteLine(text);
    this.writtenMessages.add(text);
  }
  public Boolean isFrontClear() {
    Cell frontCell = this.getFrontCell();
    if (!(Objects.equals(frontCell, null))) {
      if (frontCell.isWall) {
        return false;
      }
    } else {
      return false;
    }
    return true;
  }
  public Boolean isGrainAvailable() {
    return this.currentCell.grainCount > 0;
  }
  public Boolean isMouthEmpty() {
    return Objects.equals(this.grainInMouth, 0);
  }

  private Cell getFrontCell() {
    Cell frontCell = null;
    if (Objects.equals(this.currentDirection, Direction.EAST)) {
      frontCell = this.currentCell.east;
    } else if (Objects.equals(this.currentDirection, Direction.SOUTH)) {
      frontCell = this.currentCell.south;
    } else if (Objects.equals(this.currentDirection, Direction.WEST)) {
      frontCell = this.currentCell.west;
    } else {
      frontCell = this.currentCell.north;
    }
    return frontCell;
  }

  public Integer grainInMouth = 0;
  public Cell currentCell;

  public Direction currentDirection = Direction.EAST;
  public List<String> writtenMessages = new LinkedList<>();
}
