package HamsterSimulatorLanguage.sandbox.HamsterLibrary;

/*Generated by MPS */


public abstract class HamsterProgramBase {
  public abstract void execute();

  public Territory territory;
  public Hamster hamster;
}
