package HamsterSimulatorLanguage.sandbox.HamsterLibrary;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class Row {
  public Row(Integer columns) {
    for (int columnIndex = 1; columnIndex <= columns; columnIndex++) {
      Cell cell = new Cell();
      if (columnIndex > 1) {
        Cell leftCell = this.cells.get(columnIndex - 1 - 1);
        cell.west = leftCell;
        leftCell.east = cell;
      }
      this.cells.add(cell);
    }
  }

  public List<Cell> cells = new LinkedList<>();
}
