package HamsterSimulatorLanguage.sandbox.HamsterLibrary;

/*Generated by MPS */

import java.util.List;
import java.util.LinkedList;

public class Territory {
  public Territory(Integer rows, Integer columns) {
    for (int rowIndex = 1; rowIndex <= rows; rowIndex++) {
      Row row = new Row(columns);
      this.rows.add(row);

      if (rowIndex > 1) {
        Row upperRow = this.rows.get(rowIndex - 1 - 1);
        for (int columnIndex = 1; columnIndex <= columns; columnIndex++) {
          Cell upperRowCell = upperRow.cells.get(columnIndex - 1);
          Cell currentRowCell = row.cells.get(columnIndex - 1);
          currentRowCell.north = upperRowCell;
          upperRowCell.south = currentRowCell;
        }
      }

    }
  }
  public Cell getCellAt(Integer x, Integer y) {
    Row row = this.rows.get(y + 1 - 1);
    Cell cell = row.cells.get(x + 1 - 1);
    return cell;
  }

  public List<Row> rows = new LinkedList<>();
}
