package HamsterSimulatorLanguage.sandbox;

/*Generated by MPS */


/**
 * 
 */
public class ActivityHelloPauleMain {
  public static void HelloPauleMain() {
    new HelloPauleHamsterProgram().execute();
  }
  public static void main(String[] args) {
    HelloPauleMain();
  }
}
