package HamsterSimulatorLanguage.sandbox;

/*Generated by MPS */


/**
 * 
 */
public class ActivityDemoMain {
  public static void DemoMain() {
    new DemoHamsterProgram().execute();
  }
  public static void main(String[] args) {
    DemoMain();
  }
}
