package HamsterSimulatorLanguage.sandbox;

/*Generated by MPS */

import org.junit.jupiter.api.Test;
import org.junit.Assert;
import wrappers.javaWrappers.IntegerFunctions;

public class HamsterTestSuite_Test {
  @Test
  public void test_Demo() throws Exception {
    DemoHamsterProgram sut = new DemoHamsterProgram();
    sut.execute();
    Assert.assertEquals("Expected $grains grains, but hamster has " + IntegerFunctions.ToString(sut.hamster.grainInMouth), Integer.valueOf(sut.hamster.grainInMouth), sut.hamster.grainInMouth);
    Assert.assertEquals(Integer.valueOf(sut.territory.getCellAt(1, 5).grainCount), sut.territory.getCellAt(1, 5).grainCount);
    Assert.assertEquals(Integer.valueOf(7), Integer.valueOf(sut.hamster.writtenMessages.size()));
    Assert.assertEquals("mouth is empty!", sut.hamster.writtenMessages.get(1 - 1));
    Assert.assertEquals("paule got a grain", sut.hamster.writtenMessages.get(2 - 1));
    Assert.assertEquals("paule put the grain back", sut.hamster.writtenMessages.get(3 - 1));
    Assert.assertEquals("mouth is empty!", sut.hamster.writtenMessages.get(4 - 1));
    Assert.assertEquals("Looking to north!", sut.hamster.writtenMessages.get(5 - 1));
    Assert.assertEquals("Looking to north!", sut.hamster.writtenMessages.get(6 - 1));
    Assert.assertEquals("Looking to north!", sut.hamster.writtenMessages.get(7 - 1));
  }
}
