package HamsterSimulatorLanguage.sandbox;

/*Generated by MPS */

import HamsterSimulatorLanguage.sandbox.HamsterLibrary.HamsterProgramBase;
import HamsterSimulatorLanguage.sandbox.HamsterLibrary.Territory;
import HamsterSimulatorLanguage.sandbox.HamsterLibrary.Cell;
import HamsterSimulatorLanguage.sandbox.HamsterLibrary.Hamster;
import HamsterSimulatorLanguage.sandbox.HamsterLibrary.Direction;

public class HelloPauleHamsterProgram extends HamsterProgramBase {
  public HelloPauleHamsterProgram() {
    this.territory = new Territory(2, 2);

    this.territory.getCellAt(0, 0).isWall = true;

    Cell hamsterCell = this.territory.getCellAt(0, 0);
    this.hamster = new Hamster(hamsterCell);
    this.hamster.grainInMouth = 0;
    this.hamster.currentDirection = Direction.EAST;
  }

  @Override
  public void execute() {
    this.hamster.write("Hello Paule");
  }
}
