name: Java Build using Gradle Wrapper

on:
  workflow_call:

env:
  PROJECT_NAME: "mps-alfi-samples"
  ARCHIVE_NAME: "mps-alfi-samples"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Install Xvfb for avoiding X11 window server AWTError when running tests (https://arbitrary-but-fixed.net/2022/01/21/headless-gui-github-actions.html)
      - name: Setup xvfb for X11 window server
        run: Xvfb :1 -screen 0 1600x1200x24 &

      # Prepare MPS
      - name: Download and Prepare MPS
        run: sh ./gradlew prepareMps

      # Build Project
      - name: Build Project
        run: sh ./gradlew mpsBuild

      # Test Project
      - name: Test Project
        run: sh ./gradlew mpsTest
        env:
          DISPLAY: :1

      # Run Java Generations
      - name: Test Java Hamster Program
        run: sh ./gradlew executeJavaHamsterTests
      - name: Test Java SWC Program
        run: sh ./gradlew executeJavaSwcTests

      # Run ALF Generations
      - name: Test ALF Hamster Program
        run: sh ./gradlew executeAlfHamsterTests
      - name: Test ALF SWC Tests
        run: sh ./gradlew executeAlfSwcTests

      # Stop Xvfb
      - name: Tear down xvfb
        run: killall Xvfb

      # Archive Artifacts
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            build/artifacts/${{ env.PROJECT_NAME }}/${{ env.ARCHIVE_NAME }}.zip

      # Archive Code
      - name: Package Code
        run: sh ./gradlew packageGeneratedCode
      - name: Archive Code
        uses: actions/upload-artifact@v3
        with:
          name: alfi-samples-code
          path: |
            build/code-gen
